# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  #schedule:
    # runs every day at 7:00 AM UTC in Jan, Feb, Sep-Dec
   # - cron:  '0 7 * 1,2,9-12 *'

name: Update drivecharts

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # - {os: macOS-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::., ropensci/piggyback, any::purrr

      - name: Run update script
        run: Rscript -e 'source("auto/update_drivecharts.R")'

      - name: Commit completed games
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add auto/saved_games.csv
          git commit -m "drivecharts updated `date`" || echo "No changes to commit"
          git push || echo "No changes to commit"
